### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by sh-bd** [kamrullab/idm#3]
The [main repo](https://github.com/WindowsAddict/IDM-Activation-Script) of this project doesn't work anymore! 

Does it still work or same as the main repo?

**Comment by mosmduali** [comment]
yes

**Comment by sh-bd** [comment]
@mosmduali isn't this repo same with the original one? If that doesn't work anymore, how is it working?

**Comment by mosmduali** [comment]
bu repo çalışıyor hiç bir sorunu yok

**Comment by kamrullab** [comment]
Hi **sh-bd**,

You're absolutely correct—**the main repo and this repo are the same**, and neither work with the latest updates. This version will only work if you **roll back to a previous trial version**, but beyond that, it won’t function as expected.

**Hope this clears things up!**

**Comment by stish834** [comment]
So, which version of IDM should i install to run this code? are you gyus planing to publish new code or hack of IDM.
